// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhanTichCamXucVanBan.Data;

#nullable disable

namespace PhanTichCamXucVanBan.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240318050118_Initialized1")]
    partial class Initialized1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhanTichCamXucVanBan.Models.CamXuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("HaiLong")
                        .HasColumnType("float");

                    b.Property<double>("KhaHaiLong")
                        .HasColumnType("float");

                    b.Property<string>("KhongGian")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("KhongHaiLong")
                        .HasColumnType("float");

                    b.Property<double>("RatHaiLong")
                        .HasColumnType("float");

                    b.Property<double>("RatKhongHaiLong")
                        .HasColumnType("float");

                    b.Property<string>("ThaiDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ThatVong")
                        .HasColumnType("float");

                    b.Property<string>("ThucAn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("camXucs");
                });
#pragma warning restore 612, 618
        }
    }
}
